FROM python:3.10-slim

WORKDIR /app

COPY /frontend .
COPY /pipelines ./pipelines
COPY setup.py .

RUN pip install -r requirements.txt
RUN pip install .

EXPOSE 8050

CMD ["streamlit", "run", "poker_interface.py", "--server.port", "8050"]

# streamlit run poker_interface.py --server.port 8050